#!/bin/sh

### BEGIN INIT INFO
# Provides:          androidoverlinux init
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: androidoverlinux init script
# Description:       initscript by djjproject
### END INIT INFO

do_start() {
    /etc/init.d/hostname.sh start
    sysctl --system
}

do_stop() {

}

case "$1" in
  start)
    do_start
  ;;
  stop)
    do_stop
  ;;
  restart)
  ;;
  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
  ;;
esac

exit 0
