#!/bin/bash

echo "[info] get update file..."
rm -rf /usr/aolupdate/* > /dev/null
wget https://github.com/djjproject/android_over_linux_update/archive/master.zip -P /usr/aolupdate > /dev/null 2>&1

echo "[info] unzip update file..."
cd /usr/aolupdate
unzip /usr/aolupdate/master.zip > /dev/null
rm /usr/aolupdate/master.zip
cd /usr/aolupdate/android_over_linux_update-master
mv /usr/aolupdate/android_over_linux_update-master/* ../
cd ..
rm -rf /usr/aolupdate/android_over_linux_update-master
chmod a+x /usr/aolupdate/*

CHECK=0
while [ $CHECK -eq 0 ]
	do
		CUR_VER=`cat /linux.prop | cut -c 24-31`
		if [ -f '/usr/aolupdate/'$CUR_VER ]; then
			read -p "[alert] apply update for $CUR_VER? (y or n) : " INPUT

			case $INPUT in
       				y)
					'/usr/aolupdate/'$CUR_VER
                			;;
       				n)
                			echo "[info] user aborted."
					;;
        			*)
               				;;
			esac

		else
			echo "[info] current : $CUR_VER"
			CHECK=1
		fi
	done

rm -rf /usr/aolupdate/*

exit 0
