#!/bin/sh

### BEGIN INIT INFO
# Provides:          aolconfig
# Required-Start:    hostname $local_fs
# Required-Stop:     
# Default-Start:     1 2 3 4 5
# Default-Stop:      
# Short-Description: androidoverlinux config script
# Description:       config by djjproject
### END INIT INFO

do_start() {
    # AOL INIT SCRIPT
    rm /var/lib/plexmediaserver/Plex\ Media\ Server/plexmediaserver.pid
    mkdir /dev/net
    ln -s /dev/tun /dev/net/tun
    ln -s /dev/block/* /dev

    # disk uuid mount
    ls -1 /mnt/media_rw/ > /dev/diskname
    blkid | grep sd | sed -n 's/.*UUID=\"\([^\"]*\)\".*/\1/p' > /dev/uuidname
    paste /dev/diskname /dev/uuidname > /dev/automount

    cat /dev/automount | while read block uuid
    do
        mkdir -p '/mnt/media_rw/by-uuid/'$uuid
        mount -o bind '/mnt/media_rw/'$block '/mnt/media_rw/by-uuid/'$uuid
    done
}

case "$1" in
  start)
    do_start
  ;;
  stop)

  ;;
  restart)

  ;;
  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
  ;;
esac

exit 0
