#!/bin/sh

### BEGIN INIT INFO
# Provides:          aolinit
# Required-Start:    $remote_fs $all
# Required-Stop:     $remote_fs $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: aolinit init script
# Description:       initscript by djjproject
### END INIT INFO

do_start() {
    su root -c "/etc/init.d/hostname.sh start"
    su root -c "sysctl --system"
}

case "$1" in
  start)
    do_start
  ;;
  stop)

  ;;
  restart)

  ;;
  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
  ;;
esac

exit 0
